#: __init__.py:97
msgid "NextGIS geoinformation system"
msgstr "Геоинформационная система NextGIS"

#: __init__.py:219
msgid "Linux kernel"
msgstr "Ядро Linux"

#: __init__.py:222
msgid "OS distribution"
msgstr "Дистрибутив ОС"

#: __init__.py:234
msgid "CPU"
msgstr "Процессор"

#: __init__.py:238
msgid "RAM"
msgstr "ОЗУ"

#: exception.py:90
msgid "Validation error"
msgstr "Ошибка валидации"

#: exception.py:95
msgid "Forbidden"
msgstr "Запрещено"

#: exception.py:100
msgid "Insufficient permissions"
msgstr "Недостаточно прав"

#: exception.py:105
msgid "Operational error"
msgstr "Операционная ошибка"

#: exception.py:110
msgid "External service error"
msgstr "Ошибка внешнего сервиса"

#: storage.py:222
msgid "Estimation is already running"
msgstr "Процесс оценки хранилища уже запущен"

#: test/test_exception.py:75
#, python-format
msgid "The answer is %d"
msgstr "Ответ %d"

